import { jsPDF } from 'jspdf';
import { ChatMessage } from '../types';

export function exportChatToPdf(
  messages: ChatMessage[],
  projectName: string,
  projectDescription?: string
): void {
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'pt',
    format: 'a4',
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 40;
  const contentWidth = pageWidth - margin * 2;
  let y = margin;

  // Header background banner
  doc.setFillColor(23, 23, 23);
  doc.rect(margin, y, contentWidth, 54, 'F');

  // Title
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.text('AXON Mobile Workspace', margin + 14, y + 24);

  // Subtitle / Project Name
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(200, 200, 200);
  const projectHeader = `Project: ${projectName} • Exported: ${new Date().toLocaleDateString()}`;
  doc.text(projectHeader, margin + 14, y + 42);

  y += 68;

  if (projectDescription) {
    doc.setFontSize(9);
    doc.setFont('helvetica', 'italic');
    doc.setTextColor(110, 110, 110);
    const descLines = doc.splitTextToSize(`Context: ${projectDescription}`, contentWidth);
    doc.text(descLines, margin, y);
    y += descLines.length * 12 + 10;
  }

  // Draw separator line
  doc.setDrawColor(220, 220, 220);
  doc.setLineWidth(0.75);
  doc.line(margin, y, margin + contentWidth, y);
  y += 16;

  // Message entries
  for (const msg of messages) {
    const isUser = msg.sender === 'user';
    const senderName = isUser ? 'User' : 'AXON';
    const timestamp = msg.timestamp || '';
    const headerText = `${senderName} • ${timestamp}${msg.modelUsed ? ` (${msg.modelUsed})` : ''}`;

    // Split body into wrapped lines
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    const bodyLines = doc.splitTextToSize(msg.text, contentWidth - 24);
    const boxHeight = bodyLines.length * 13 + 28;

    // Check if box fits on current page
    if (y + boxHeight > pageHeight - margin) {
      doc.addPage();
      y = margin;
    }

    // Message box background
    if (isUser) {
      doc.setFillColor(245, 245, 245);
      doc.setDrawColor(220, 220, 220);
    } else {
      doc.setFillColor(250, 250, 250);
      doc.setDrawColor(210, 210, 210);
    }

    doc.roundedRect(margin, y, contentWidth, boxHeight, 4, 4, 'FD');

    // Header inside box
    doc.setFontSize(8.5);
    doc.setFont('helvetica', 'bold');
    if (isUser) {
      doc.setTextColor(40, 40, 40);
    } else {
      doc.setTextColor(0, 100, 200);
    }
    doc.text(headerText, margin + 12, y + 14);

    // Body text inside box
    doc.setFontSize(9.5);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(30, 30, 30);
    doc.text(bodyLines, margin + 12, y + 28);

    y += boxHeight + 10;
  }

  // Page numbering footer
  const totalPages = doc.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(150, 150, 150);
    doc.text(
      `Page ${i} of ${totalPages} • Generated by AXON Mobile Engine`,
      pageWidth / 2,
      pageHeight - 20,
      { align: 'center' }
    );
  }

  const safeName = projectName.toLowerCase().replace(/[^a-z0-9]+/g, '-');
  doc.save(`axon-chat-${safeName}-${Date.now()}.pdf`);
}
