import { jsPDF } from 'jspdf';
import html2canvas from 'html2canvas';
import { ChatMessage } from '../types';

export function exportChatToPdf(
  messages: ChatMessage[],
  projectName: string,
  projectDescription?: string
): void {
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'pt',
    format: 'a4',
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 40;
  const contentWidth = pageWidth - margin * 2;
  let y = margin;

  // Header background banner
  doc.setFillColor(23, 23, 23);
  doc.rect(margin, y, contentWidth, 54, 'F');

  // Title
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.text('AXON Mobile Workspace', margin + 14, y + 24);

  // Subtitle / Project Name
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(200, 200, 200);
  const projectHeader = `Project: ${projectName} • Exported: ${new Date().toLocaleDateString()}`;
  doc.text(projectHeader, margin + 14, y + 42);

  y += 68;

  if (projectDescription) {
    doc.setFontSize(9);
    doc.setFont('helvetica', 'italic');
    doc.setTextColor(110, 110, 110);
    const descLines = doc.splitTextToSize(`Context: ${projectDescription}`, contentWidth);
    doc.text(descLines, margin, y);
    y += descLines.length * 12 + 10;
  }

  // Draw separator line
  doc.setDrawColor(220, 220, 220);
  doc.setLineWidth(0.75);
  doc.line(margin, y, margin + contentWidth, y);
  y += 16;

  // Message entries
  for (const msg of messages) {
    const isUser = msg.sender === 'user';
    const senderName = isUser ? 'User' : 'AXON';
    const timestamp = msg.timestamp || '';
    const headerText = `${senderName} • ${timestamp}${msg.modelUsed ? ` (${msg.modelUsed})` : ''}`;

    // Split body into wrapped lines
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    const bodyLines = doc.splitTextToSize(msg.text, contentWidth - 24);
    const boxHeight = bodyLines.length * 13 + 28;

    // Check if box fits on current page
    if (y + boxHeight > pageHeight - margin) {
      doc.addPage();
      y = margin;
    }

    // Message box background
    if (isUser) {
      doc.setFillColor(245, 245, 245);
      doc.setDrawColor(220, 220, 220);
    } else {
      doc.setFillColor(250, 250, 250);
      doc.setDrawColor(210, 210, 210);
    }

    doc.roundedRect(margin, y, contentWidth, boxHeight, 4, 4, 'FD');

    // Header inside box
    doc.setFontSize(8.5);
    doc.setFont('helvetica', 'bold');
    if (isUser) {
      doc.setTextColor(40, 40, 40);
    } else {
      doc.setTextColor(0, 100, 200);
    }
    doc.text(headerText, margin + 12, y + 14);

    // Body text inside box
    doc.setFontSize(9.5);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(30, 30, 30);
    doc.text(bodyLines, margin + 12, y + 28);

    y += boxHeight + 10;
  }

  // Page numbering footer
  const totalPages = doc.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(150, 150, 150);
    doc.text(
      `Page ${i} of ${totalPages} • Generated by AXON Mobile Engine`,
      pageWidth / 2,
      pageHeight - 20,
      { align: 'center' }
    );
  }

  const safeName = projectName.toLowerCase().replace(/[^a-z0-9]+/g, '-');
  doc.save(`axon-chat-${safeName}-${Date.now()}.pdf`);
}

/**
 * Image PDF: Produces a PDF made of complete image content covering the entire
 * chat conversation from its very first message to its last, capturing every message in full.
 */
export async function exportChatToImagePdf(
  messages: ChatMessage[],
  projectName: string,
  projectDescription?: string,
  providedElement?: HTMLElement | null
): Promise<void> {
  let targetElement: HTMLElement;
  let didCreateElement = false;

  if (providedElement) {
    targetElement = providedElement;
  } else {
    didCreateElement = true;
    targetElement = document.createElement('div');
    targetElement.id = 'temp-image-pdf-stage';
    targetElement.style.position = 'fixed';
    targetElement.style.left = '-9999px';
    targetElement.style.top = '0';
    targetElement.style.width = '760px';
    targetElement.style.backgroundColor = '#0a0a0a';
    targetElement.style.color = '#ffffff';
    targetElement.style.padding = '32px 28px';
    targetElement.style.fontFamily = '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif';
    targetElement.style.zIndex = '-9999';
    targetElement.style.boxSizing = 'border-box';

    // Header section
    const header = document.createElement('div');
    header.style.borderBottom = '1px solid #262626';
    header.style.paddingBottom = '16px';
    header.style.marginBottom = '20px';

    const title = document.createElement('h1');
    title.style.margin = '0 0 4px 0';
    title.style.fontSize = '20px';
    title.style.fontWeight = 'bold';
    title.textContent = `AXON • ${projectName}`;
    header.appendChild(title);

    if (projectDescription) {
      const desc = document.createElement('p');
      desc.style.margin = '0 0 6px 0';
      desc.style.fontSize = '12px';
      desc.style.color = '#a3a3a3';
      desc.textContent = projectDescription;
      header.appendChild(desc);
    }

    const meta = document.createElement('div');
    meta.style.fontSize = '11px';
    meta.style.color = '#737373';
    meta.textContent = `${new Date().toLocaleDateString(undefined, { year: 'numeric', month: 'short', day: 'numeric' })} • Full Conversation Archive (${messages.length} messages)`;
    header.appendChild(meta);

    targetElement.appendChild(header);

    // Render every message from first to last
    for (const msg of messages) {
      const isAxon = msg.sender === 'axon' || (msg as any).role === 'assistant';
      const row = document.createElement('div');
      row.style.display = 'flex';
      row.style.flexDirection = 'column';
      row.style.alignItems = isAxon ? 'flex-start' : 'flex-end';
      row.style.marginBottom = '14px';

      const bubble = document.createElement('div');
      bubble.style.maxWidth = '85%';
      bubble.style.padding = '12px 16px';
      bubble.style.borderRadius = '16px';
      bubble.style.fontSize = '13px';
      bubble.style.lineHeight = '1.5';
      bubble.style.boxSizing = 'border-box';

      if (isAxon) {
        bubble.style.backgroundColor = '#171717';
        bubble.style.color = '#f5f5f5';
        bubble.style.border = '1px solid #262626';
      } else {
        bubble.style.backgroundColor = '#ffffff';
        bubble.style.color = '#000000';
      }

      const senderTag = document.createElement('div');
      senderTag.style.fontSize = '10px';
      senderTag.style.fontWeight = 'bold';
      senderTag.style.marginBottom = '4px';
      senderTag.style.opacity = '0.7';
      senderTag.textContent = isAxon ? 'AXON' : 'User';
      bubble.appendChild(senderTag);

      const text = document.createElement('div');
      text.style.whiteSpace = 'pre-wrap';
      text.style.wordBreak = 'break-word';
      text.textContent = typeof msg.text === 'string' ? msg.text : JSON.stringify(msg.text);
      bubble.appendChild(text);

      const time = document.createElement('div');
      time.style.fontSize = '9px';
      time.style.marginTop = '6px';
      time.style.opacity = '0.6';
      time.style.textAlign = 'right';
      time.textContent = msg.timestamp || '';
      bubble.appendChild(time);

      row.appendChild(bubble);
      targetElement.appendChild(row);
    }

    document.body.appendChild(targetElement);
  }

  try {
    const canvas = await html2canvas(targetElement, {
      scale: 2,
      useCORS: true,
      logging: false,
      backgroundColor: '#0a0a0a',
      windowWidth: 760,
    });

    const doc = new jsPDF({
      orientation: 'portrait',
      unit: 'pt',
      format: 'a4',
    });

    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();
    const margin = 20;
    const printableWidth = pageWidth - margin * 2;
    const printableHeight = pageHeight - margin * 2;

    const canvasRatio = canvas.width / printableWidth;
    const maxChunkCanvasHeight = Math.floor(printableHeight * canvasRatio);

    let yOffset = 0;
    let pageNumber = 0;

    while (yOffset < canvas.height) {
      if (pageNumber > 0) {
        doc.addPage();
      }

      const currentChunkHeight = Math.min(maxChunkCanvasHeight, canvas.height - yOffset);

      const chunkCanvas = document.createElement('canvas');
      chunkCanvas.width = canvas.width;
      chunkCanvas.height = currentChunkHeight;
      const chunkCtx = chunkCanvas.getContext('2d');

      if (chunkCtx) {
        chunkCtx.fillStyle = '#0a0a0a';
        chunkCtx.fillRect(0, 0, chunkCanvas.width, currentChunkHeight);
        chunkCtx.drawImage(
          canvas,
          0,
          yOffset,
          canvas.width,
          currentChunkHeight,
          0,
          0,
          canvas.width,
          currentChunkHeight
        );

        const chunkData = chunkCanvas.toDataURL('image/jpeg', 0.95);
        const renderedHeight = currentChunkHeight / canvasRatio;
        doc.addImage(chunkData, 'JPEG', margin, margin, printableWidth, renderedHeight);
      }

      yOffset += currentChunkHeight;
      pageNumber++;
    }

    const totalPages = doc.getNumberOfPages();
    for (let i = 1; i <= totalPages; i++) {
      doc.setPage(i);
      doc.setFontSize(8);
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(140, 140, 140);
      doc.text(
        `Page ${i} of ${totalPages} • Complete Visual Archive (${messages.length} messages) • AXON`,
        pageWidth / 2,
        pageHeight - 8,
        { align: 'center' }
      );
    }

    const safeName = projectName.toLowerCase().replace(/[^a-z0-9]+/g, '-');
    doc.save(`axon-visual-chat-${safeName}-${Date.now()}.pdf`);
  } finally {
    if (didCreateElement && targetElement.parentNode) {
      targetElement.parentNode.removeChild(targetElement);
    }
  }
}

